setwd("C:/Users/Bhuvanesh/Documents/R")
a=read.csv("heart_failure_clinical_records_dataset.csv")
a
hist(a$age)
hist(a$anaemia)
hist(a$creatinine_phosphokinase)
hist(a$diabetes)
hist(a$ejection_fraction)
hist(a$high_blood_pressure)
hist(a$platelets)
hist(a$serum_creatinine)
hist(a$serum_sodium)
hist(a$sex)
hist(a$smoking)
hist(a$time)
hist(a$DEATH_EVENT)




barplot(a$age)
barplot(a$anaemia)
barplot(a$creatinine_phosphokinase)
barplot(a$diabetes)
barplot(a$ejection_fraction)
barplot(a$high_blood_pressure)
barplot(a$platelets)
barplot(a$serum_creatinine)
barplot(a$serum_sodium)
barplot(a$sex)
barplot(a$smoking)
barplot(a$time)
barplot(a$DEATH_EVENT)



boxplot(a$age)
boxplot(a$anaemia)
boxplot(a$creatinine_phosphokinase)
boxplot(a$diabetes)
boxplot(a$ejection_fraction)
boxplot(a$high_blood_pressure)
boxplot(a$platelets)
boxplot(a$serum_creatinine)
boxplot(a$serum_sodium)
boxplot(a$sex)
boxplot(a$smoking)
boxplot(a$time)
boxplot(a$DEATH_EVENT)


pie(a$age)
pie(a$anaemia)
pie(a$creatinine_phosphokinase)
pie(a$diabetes)
pie(a$ejection_fraction)
pie(a$high_blood_pressure)
pie(a$platelets)
pie(a$serum_creatinine)
pie(a$serum_sodium)
pie(a$sex)
pie(a$smoking)
pie(a$time)
pie(a$DEATH_EVENT)

plot(a$age,type="o")
plot(a$anaemia,type="o")
plot(a$creatinine_phosphokinase,type="o")
plot(a$diabetes,type="o")
plot(a$ejection_fraction,type="o")
plot(a$high_blood_pressure,type="o")
plot(a$platelets,type="o")
plot(a$serum_creatinine,type="o")
plot(a$serum_sodium,type="o")
plot(a$sex,type="o")
plot(a$smoking,type="o")
plot(a$time,type="o")
plot(a$DEATH_EVENT,type="o")



plot(a$age)
plot(a$anaemia)
plot(a$creatinine_phosphokinase)
plot(a$diabetes)
plot(a$ejection_fraction)
plot(a$high_blood_pressure)
plot(a$platelets)
plot(a$serum_creatinine)
plot(a$serum_sodium)
plot(a$sex)
plot(a$smoking)
plot(a$time)
plot(a$DEATH_EVENT)
